/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/Applicants/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Qualification?: string;
                    MinExperience?: number | string;
                    City?: string;
                    JobListingId?: string;
                    Page?: number | string;
                    PageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{jobListingId}/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobListingId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ListingApplicantResponse"][];
                        "application/json": components["schemas"]["ListingApplicantResponse"][];
                        "text/json": components["schemas"]["ListingApplicantResponse"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobListingId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{jobListingId}/applications/{applicantId}/cv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobListingId: string;
                    applicantId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    stage?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MyApplicationResponse"][];
                        "application/json": components["schemas"]["MyApplicationResponse"][];
                        "text/json": components["schemas"]["MyApplicationResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/me/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MyApplicationsSummaryResponse"];
                        "application/json": components["schemas"]["MyApplicationsSummaryResponse"];
                        "text/json": components["schemas"]["MyApplicationsSummaryResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/me/{jobListingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobListingId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MyApplicationStatusResponse"];
                        "application/json": components["schemas"]["MyApplicationStatusResponse"];
                        "text/json": components["schemas"]["MyApplicationStatusResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{jobListingId}/{applicantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobListingId: string;
                    applicantId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{jobListingId}/{applicantId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobListingId: string;
                    applicantId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateApplicationStatusRequest"];
                    "text/json": components["schemas"]["UpdateApplicationStatusRequest"];
                    "application/*+json": components["schemas"]["UpdateApplicationStatusRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/Auth/register/applicant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterApplicantRequest"];
                    "text/json": components["schemas"]["RegisterApplicantRequest"];
                    "application/*+json": components["schemas"]["RegisterApplicantRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResponse"];
                        "application/json": components["schemas"]["AuthResponse"];
                        "text/json": components["schemas"]["AuthResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Auth/register/employer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterEmployerRequest"];
                    "text/json": components["schemas"]["RegisterEmployerRequest"];
                    "application/*+json": components["schemas"]["RegisterEmployerRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResponse"];
                        "application/json": components["schemas"]["AuthResponse"];
                        "text/json": components["schemas"]["AuthResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResponse"];
                        "application/json": components["schemas"]["AuthResponse"];
                        "text/json": components["schemas"]["AuthResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CompanyResponse"][];
                        "application/json": components["schemas"]["CompanyResponse"][];
                        "text/json": components["schemas"]["CompanyResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Location?: string;
                    EmploymentType?: components["schemas"]["JobType"];
                    SalaryMin?: number | string;
                    SalaryMax?: number | string;
                    CompanyId?: string;
                    Sort?: string;
                    Dir?: string;
                    Page?: number | string;
                    PageSize?: number | string;
                    Q?: string;
                    PostedSince?: string;
                    RemoteOnly?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateJobListingRequest"];
                    "text/json": components["schemas"]["CreateJobListingRequest"];
                    "application/*+json": components["schemas"]["CreateJobListingRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Jobs/filter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    title?: string;
                    location?: string;
                    type?: components["schemas"]["JobType"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["JobListingResponse"][];
                        "application/json": components["schemas"]["JobListingResponse"][];
                        "text/json": components["schemas"]["JobListingResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["JobListingDetailResponse"];
                        "application/json": components["schemas"]["JobListingDetailResponse"];
                        "text/json": components["schemas"]["JobListingDetailResponse"];
                    };
                };
                /** @description Not Modified */
                304: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateJobListingRequest"];
                    "text/json": components["schemas"]["UpdateJobListingRequest"];
                    "application/*+json": components["schemas"]["UpdateJobListingRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/Jobs/company/{companyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Location?: string;
                    EmploymentType?: components["schemas"]["JobType"];
                    SalaryMin?: number | string;
                    SalaryMax?: number | string;
                    CompanyId?: string;
                    Sort?: string;
                    Dir?: string;
                    Page?: number | string;
                    PageSize?: number | string;
                    Q?: string;
                    PostedSince?: string;
                    RemoteOnly?: boolean;
                };
                header?: never;
                path: {
                    companyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Jobs/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["JobListingResponse"][];
                        "application/json": components["schemas"]["JobListingResponse"][];
                        "text/json": components["schemas"]["JobListingResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Jobs/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["JobListingStatsResponse"][];
                        "application/json": components["schemas"]["JobListingStatsResponse"][];
                        "text/json": components["schemas"]["JobListingStatsResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApplicationStatus: number;
        AuthResponse: {
            token: string;
            /** Format: uuid */
            userId: string;
            email: string;
            role: string;
            /** Format: uuid */
            companyId: null | string;
            fullName: string;
        };
        CompanyResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            city: string;
            province: string;
            industry: string;
            website: string;
            /** Format: int32 */
            foundedYear: null | number | string;
            /** Format: int64 */
            activeListingCount: number | string;
        };
        CreateJobListingRequest: {
            title: string;
            description: string;
            minimumRequirements: string;
            location: string;
            type: components["schemas"]["JobType"];
            /** Format: double */
            salaryMin: null | number | string;
            /** Format: double */
            salaryMax: null | number | string;
            /** Format: date-time */
            expiresAt: string;
            responsibilities?: null | string[];
            skills?: null | string[];
            /**
             * Format: int32
             * @default 0
             */
            minimumExperienceYears: number | string;
        };
        JobListingDetailResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            description: string;
            minimumRequirements: string;
            location: string;
            type: string;
            /** Format: double */
            salaryMin: null | number | string;
            /** Format: double */
            salaryMax: null | number | string;
            status: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: uuid */
            companyId: string;
            companyName: string;
            companyCity: string;
            companyProvince: string;
            companyWebsite: string;
            responsibilities: string[];
            skills: string[];
            /** Format: int32 */
            minimumExperienceYears: number | string;
            /** Format: int32 */
            applicantCount: number | string;
        };
        JobListingResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            location: string;
            type: string;
            /** Format: double */
            salaryMin: null | number | string;
            /** Format: double */
            salaryMax: null | number | string;
            status: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: uuid */
            companyId: string;
            companyName: string;
            companyCity: string;
            responsibilities: string[];
            skills: string[];
            /** Format: int32 */
            minimumExperienceYears: number | string;
            /** Format: int32 */
            applicantCount: number | string;
        };
        JobListingStatsResponse: {
            /** Format: uuid */
            jobListingId: string;
            title: string;
            /** Format: int64 */
            totalApplications: number | string;
            /** Format: int64 */
            submitted: number | string;
            /** Format: int64 */
            underReview: number | string;
            /** Format: int64 */
            shortlisted: number | string;
            /** Format: int64 */
            rejected: number | string;
            /** Format: int64 */
            offered: number | string;
            /** Format: int64 */
            rank: number | string;
        };
        JobType: number;
        ListingApplicantResponse: {
            /** Format: uuid */
            jobListingId: string;
            /** Format: uuid */
            applicantId: string;
            fullName: string;
            email: string;
            city: string;
            /** Format: int32 */
            yearsOfExperience: number | string;
            coverNote: string;
            selectedSkills: string[];
            status: string;
            stage: string;
            /** Format: date-time */
            submittedAt: string;
            hasCv: boolean;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        MyApplicationResponse: {
            /** Format: uuid */
            jobListingId: string;
            jobTitle: string;
            companyName: string;
            status: string;
            stage: string;
            /** Format: date-time */
            submittedAt: string;
        };
        MyApplicationsSummaryResponse: {
            /** Format: int32 */
            total: number | string;
            /** Format: int32 */
            applied: number | string;
            /** Format: int32 */
            pending: number | string;
            /** Format: int32 */
            accepted: number | string;
            /** Format: int32 */
            rejected: number | string;
        };
        MyApplicationStatusResponse: {
            /** Format: uuid */
            jobListingId: string;
            jobTitle: string;
            companyName: string;
            status: string;
            stage: string;
            /** Format: date-time */
            submittedAt: string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        RegisterApplicantRequest: {
            fullName: string;
            email: string;
            password: string;
        };
        RegisterEmployerRequest: {
            fullName: string;
            email: string;
            password: string;
            /** Format: uuid */
            companyId: string;
        };
        UpdateApplicationStatusRequest: {
            status: components["schemas"]["ApplicationStatus"];
        };
        UpdateJobListingRequest: {
            title: null | string;
            description: null | string;
            location: null | string;
            employmentType: null | components["schemas"]["JobType"];
            /** Format: double */
            salaryMin: null | number | string;
            /** Format: double */
            salaryMax: null | number | string;
            /** Format: date-time */
            expiresAt: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
